const cartId = localStorage.getItem('nordicshop-cart') || crypto.randomUUID();
localStorage.setItem('nordicshop-cart', cartId);
let products = [], category = 'All';
const money = n => `${Number(n).toLocaleString('da-DK')} DKK`;

async function loadProducts(){ products = await fetch('/api/products').then(r=>r.json()); renderFilters(); renderProducts(); await loadCart(); }
function renderFilters(){ const cats=['All',...new Set(products.map(p=>p.category))]; filters.innerHTML=cats.map(c=>`<button class="chip ${c===category?'active':''}" data-category="${c}">${c}</button>`).join(''); filters.querySelectorAll('button').forEach(b=>b.onclick=()=>{category=b.dataset.category;renderFilters();renderProducts();}); }
function renderProducts(){ const shown=category==='All'?products:products.filter(p=>p.category===category); productCount.textContent=`${shown.length} pieces available`; grid.innerHTML=shown.map(p=>`<article class="card"><div class="product-art ${p.accent}" role="img" aria-label="${p.name}"></div><div class="card-body"><div class="meta">${p.category} · ${p.vendor}</div><h3>${p.name}</h3><div class="meta">${p.description}</div><div class="price-row"><span class="price">${money(p.price)}</span><button class="btn" data-add="${p.id}" ${p.stock<1?'disabled':''}>Add to bag</button></div></div></article>`).join(''); grid.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addItem(Number(b.dataset.add))); }
async function addItem(productId){ await fetch('/api/cart/items',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cart_id:cartId,product_id:productId,quantity:1})}); await loadCart(); drawer.classList.add('open'); }
async function loadCart(){ const cart=await fetch(`/api/cart/${cartId}`).then(r=>r.json()); cartCount.textContent=cart.items.reduce((n,x)=>n+x.quantity,0); cartTotal.textContent=money(cart.total); cartLines.innerHTML=cart.items.length?cart.items.map(x=>`<div class="cart-line"><div><strong>${x.name}</strong><div class="meta">${x.quantity} × ${money(x.price)}</div></div><button class="btn secondary" data-remove="${x.id}">Remove</button></div>`).join(''):'<div class="empty">Your cart is empty.</div>'; cartLines.querySelectorAll('[data-remove]').forEach(b=>b.onclick=async()=>{await fetch(`/api/cart/${cartId}/items/${b.dataset.remove}`,{method:'DELETE'});loadCart();}); }
cartButton.onclick=()=>drawer.classList.add('open'); closeCart.onclick=()=>drawer.classList.remove('open');
checkout.onsubmit=async e=>{e.preventDefault(); const data=new FormData(checkout); const response=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cart_id:cartId,customer_name:data.get('name'),customer_email:data.get('email')})}); const body=await response.json(); message.className='notice'; message.textContent=response.ok?`Thank you. Order #${body.order_id} is confirmed.`:(body.detail||'Checkout failed'); if(response.ok)loadCart();};
loadProducts();
