apiVersion: v1
kind: Secret

metadata:
  name: nordicshop-secret
  namespace: nordicshop

type: Opaque

stringData:
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: nordicshop-secret
        key: POSTGRES_PASSWORD