apiVersion: v1
kind: Secret

metadata:
  name: nordicshop-secret
  namespace: nordicshop

type: Opaque

stringData:
  NORDICSHOP_DATABASE_URL: postgresql+psycopg://USERNAME:PASSWORD@postgres:5432/DATABASE