\set ON_ERROR_STOP on

DROP TABLE IF EXISTS order_lines CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS tenants CASCADE;

CREATE TABLE tenants (
  id      integer PRIMARY KEY,
  name    varchar(100) NOT NULL UNIQUE,
  slug    varchar(60) NOT NULL UNIQUE,
  active  boolean NOT NULL DEFAULT true
);

CREATE TABLE users (
  id        integer PRIMARY KEY,
  email     varchar(160) NOT NULL UNIQUE,
  name      varchar(100) NOT NULL,
  role      varchar(30) NOT NULL,
  tenant_id integer REFERENCES tenants(id)
);

CREATE TABLE products (
  id          integer PRIMARY KEY,
  tenant_id   integer NOT NULL REFERENCES tenants(id),
  name        varchar(120) NOT NULL,
  description varchar(280) NOT NULL,
  category    varchar(60) NOT NULL,
  price       numeric(10,2) NOT NULL,
  stock       integer NOT NULL DEFAULT 0,
  accent      varchar(20) NOT NULL DEFAULT 'stone',
  active      boolean NOT NULL DEFAULT true
);

CREATE TABLE orders (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name  varchar(100) NOT NULL,
  customer_email varchar(160) NOT NULL,
  status         varchar(30) NOT NULL DEFAULT 'placed',
  created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE order_lines (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id     integer NOT NULL REFERENCES orders(id),
  tenant_id    integer NOT NULL REFERENCES tenants(id),
  product_id   integer NOT NULL REFERENCES products(id),
  product_name varchar(120) NOT NULL,
  quantity     integer NOT NULL,
  unit_price   numeric(10,2) NOT NULL
);
