apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: nordicshop-keyvault
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"

spec:
  provider: azure

  secretObjects:
    - secretName: nordicshop-runtime-secret
      type: Opaque
      data:
        - objectName: postgres-password
          key: POSTGRES_PASSWORD

        - objectName: nordicshop-database-url
          key: NORDICSHOP_DATABASE_URL

        - objectName: postgres-app-password
          key: POSTGRES_APP_PASSWORD

        - objectName: nordicshop-app-database-url
          key: NORDICSHOP_APP_DATABASE_URL

  parameters:
    usePodIdentity: "false"

    clientID: {{ .Values.azure.nordicApiClientId | quote }}

    keyvaultName: {{ .Values.azure.keyVaultName | quote }}

    tenantId: {{ .Values.azure.tenantId | quote }}

    objects: |
      array:
        - |
          objectName: postgres-password
          objectType: secret
          objectVersion: ""

        - |
          objectName: nordicshop-database-url
          objectType: secret
          objectVersion: ""

        - |
          objectName: postgres-app-password
          objectType: secret
          objectVersion: ""

        - |
          objectName: nordicshop-app-database-url
          objectType: secret
          objectVersion: ""
          