apiVersion: v1
kind: ServiceAccount

metadata:
  name: nordic-api
  namespace: {{ .Release.Namespace }}

  annotations:
    azure.workload.identity/client-id: "14d8802c-2b2f-4b6d-91cf-2709930ea2e4"
    