apiVersion: apps/v1
kind: Deployment

metadata:
  name: nordicshop-api
  namespace: {{ .Release.Namespace }}

spec:
  replicas: {{ .Values.api.replicas }}

  selector:
    matchLabels:
      app: nordicshop-api

  template:
    metadata:
      labels:
        app: nordicshop-api
        azure.workload.identity/use: "true"

    spec:
      serviceAccountName: nordic-api

      initContainers:
        - name: wait-for-postgres
          image: {{ .Values.postgres.image }}
          command:
            - sh
            - -c
            - >
              until pg_isready
              -h postgres
              -p 5432
              -U {{ .Values.postgres.user | quote }}
              -d {{ .Values.postgres.database | quote }};
              do
                echo "Waiting for PostgreSQL...";
                sleep 2;
              done

      containers:
        - name: nordicshop-api
          image: {{ .Values.api.image }}
          imagePullPolicy: IfNotPresent

          resources:
            {{ toYaml .Values.api.resources | nindent 12 }}

          ports:
            - containerPort: 8000

          volumeMounts:
            - name: secrets-store
              mountPath: /mnt/secrets-store
              readOnly: true

          env:
            - name: NORDICSHOP_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: nordicshop-runtime-secret
                  key: NORDICSHOP_DATABASE_URL

            - name: NORDICSHOP_REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: nordicshop-config
                  key: NORDICSHOP_REDIS_URL
          readinessProbe:
            httpGet:
              path: /api/ready
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10

      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: nordicshop-keyvault