apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: nordicshop-keyvault
  namespace: {{ .Release.Namespace }}

spec:
  provider: azure

  secretObjects:
    - secretName: nordicshop-runtime-secret
      type: Opaque
      data:
        - objectName: postgres-password
          key: POSTGRES_PASSWORD

        - objectName: nordicshop-database-url
          key: NORDICSHOP_DATABASE_URL

  parameters:
    usePodIdentity: "false"

    clientID: "14d8802c-2b2f-4b6d-91cf-2709930ea2e4"

    keyvaultName: "kv-nordicshop-dev-weu"

    tenantId: "ce02f814-9bb0-4eeb-a5e6-42af533c9e9f"

    objects: |
      array:
        - |
          objectName: postgres-password
          objectType: secret
          objectVersion: ""

        - |
          objectName: nordicshop-database-url
          objectType: secret
          objectVersion: ""
          