apiVersion: apps/v1
kind: Deployment

metadata:
  name: nordicshop-customer-web
  namespace: {{ .Release.Namespace }}

spec:
  replicas: {{ .Values.customerWeb.replicas }}

  selector:
    matchLabels:
      app: nordicshop-customer-web

  template:
    metadata:
      labels:
        app: nordicshop-customer-web

    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: nordicshop-customer-web
          image: {{ .Values.customerWeb.image }}
          imagePullPolicy: IfNotPresent

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

          resources:
            {{ toYaml .Values.customerWeb.resources | nindent 12 }}

          ports:
            - containerPort: 8080
          
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20