apiVersion: v1
kind: ServiceAccount

metadata:
  name: nordicshop-db-admin
  namespace: {{ .Release.Namespace }}

  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    azure.workload.identity/client-id: {{ .Values.azure.dbAdminClientId | quote }}
