apiVersion: v1
kind: Secret

metadata:
  name: nordicshop-secret
  namespace: {{ .Release.Namespace }}

type: Opaque

stringData:
  POSTGRES_PASSWORD: {{ .Values.secret.postgresPassword | quote }}
  NORDICSHOP_DATABASE_URL: {{ .Values.secret.databaseUrl | quote }}